# -*- coding: utf-8 -*-
"""NNJPA Paper Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4C8aEyK1MJluetSQb9UnMJ9htBWk-bg
"""

##Imports and Reader
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

df = pd.read_excel("Tax Credit_RawData.xlsx", sheet_name = 0)

## Revenue Graph
label_map = {
    'GIT_Rev': 'Gross Income Tax',
    'CBT_Rev': 'Corporate Business Tax',
    'Emp_518': 'Emp 518',
    'Emp_5413': 'Emp 5413',
    'Emp_5415': 'Emp 5415',
    'Emp_5416': 'Emp 5416',
    'Emp_5417': 'Emp 5417',
    'Wage_518': 'Wage 518',
    'Wage_5413': 'Wage 5413',
    'Wage_5415': 'Wage 5415',
    'Wage_5416': 'Wage 5416',
    'Wage_5417': 'Wage 5417',
    'Avg_Wages': 'Average Wages',
    'Avg_Employment': 'Average Employment',
    'Avg_Real_Wage': 'Average Real Wage'
}

for col in ['GIT_Rev', 'CBT_Rev']:

  plt.plot(df['Fiscal Years'],df[col],label=label_map[col])

plt.xlabel('Fiscal Year')
plt.ylabel('Revenue in Millions of Dollars')
plt.title('NJ Tax Revenues Since 2018')
plt.axvspan(2025,2026, color = "yellow", alpha = .2, label = "Projections")
plt.axvspan(2019.9,2020.1, color = "gray", alpha = .2,)

plt.legend()


## Innovation Credit Expenditures vs CBT + GIT Expenditure

## Employment Increase vs Wage Increases


import matplotlib.pyplot as plt

fig, ax1 = plt.subplots(figsize=(10, 6))


emp_cols = ['Avg_Employment']
for col in emp_cols:
    ax1.plot(df['Fiscal Years'], df[col] * 100, label=label_map[col], linestyle='-', marker='o', color = "black")

ax1.set_xlabel('Fiscal Year')
ax1.set_ylabel('Employment (%)')
ax1.tick_params(axis='y')

ax1.axvspan(2019.9, 2020.1, color="gray", alpha=0.2)

ax2 = ax1.twinx()
wage_cols = ['Avg_Wages', 'Avg_Real_Wage']
for col in wage_cols:
    ax2.plot(df['Fiscal Years'], df[col], label=label_map[col], linestyle='--', marker='o')

ax2.set_ylabel('Wages ($)')
ax2.tick_params(axis='y')

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left')

plt.title('NJ Employment % and Wages in Select Industries Since 2018')
plt.tight_layout()
plt.savefig("nj_employment_wages.png", dpi=300)  # Save before show()
plt.show()